# Configure Using Gemfile
#
default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/tournament_development.sqlite3

test:
  <<: *default
  database: db/tournament_test.sqlite3

production:
  primary: &primary_production
    <<: *default
    database: db/tournament_production.sqlite3

  cache:
    <<: *primary_production
    database: db/tournament_production_cache.sqlite3
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: db/tournament_production_queue.sqlite3
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: db/tournament_production_cable.sqlite3
    migrations_paths: db/cable_migrate